name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: '0 0 * * *'}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_languages: yes
          plugin_languages_ignored: dockerfile
          plugin_habits: yes
          plugin_stars: yes
          plugin_lines: yes
          plugin_traffic: yes
          plugin_projects: yes
          plugin_skyline: yes
          config_order: base.header, languages, habits, stars, lines, traffic, projects, skyline
